name: Code Scan PMD
on: push

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "11"
            - uses: pmd/pmd-github-action@v1
              with:
                  rulesets: "ruleset.xml"
            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: pmd-report.sarif
