name: telegram message test
on: pull_request
jobs:
    build:
        name: Telegram Message
        runs-on: ubuntu-latest
        steps:
            - name: send telegram message on push
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TEST_BOT_USER }}
                  token: ${{ secrets.TELEGRAM_TEST_BOT_API }}
                  message: |
                      ${{ github.actor }} created a pull request:
                      Title: ${{ github.event.pull_request.title }}
                      Target branch: ${{ github.event.pull_request.base.ref }}
                      
                      See PR: ${{ github.server_url }}/${{ github.repository }}/pulls/${{ github.event.pull_request.id }}
