name: Test Workflow
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Get changed files
              uses: jitterbit/get-changed-files@v1
